### ISSUE TITLE
Colocar el diagrama UML

### ISSUE THREAD

**Issue by yosbel-penate** [KevinPinoDelSol/Diagrama-Proyecto-DPOO#2]
Donde esta el proyecto vp?

**Comment by KevinPinoDelSol** [comment]
El proyecto lo puede encontrar en la rama Extendido. Hay algunos archivos de más que generó el Visual paradigm pero no los puedo eliminar hasta llegar a cada a casa.

**Comment by yosbel-penate** [comment]
![miomor](https://user-images.githubusercontent.com/58090876/201189519-438da0f0-5446-41a3-93bc-db402cadd5ec.png)

**Comment by yosbel-penate** [comment]
asi es como yo veo tu repositorio

**Comment by KevinPinoDelSol** [comment]
> asi es como yo veo tu repositorio
Como mencioné, el proyecto esta en la rama Extendido. No quería ponerlo en la main por otras razones.

**Comment by yosbel-penate** [comment]
a ya entendi en otra bransh

**Comment by yosbel-penate** [comment]
ya lo vi

**Comment by yosbel-penate** [comment]
Ponle nombre a los paquetes, para saber que funcion acogen

**Comment by KevinPinoDelSol** [comment]
Si no me equivoco, ya tienen nombre, aparecen en la parte superior central de cada paquete.

**Comment by yosbel-penate** [comment]
![paquete](https://user-images.githubusercontent.com/58090876/201195976-78e967bd-26fb-4add-b7f7-1f87db911b45.png)

**Comment by yosbel-penate** [comment]
La empresa tiene una lista de administradores, pero de que son administradores?

**Comment by yosbel-penate** [comment]
La empresa tiene una lista de gerentes, pero que gerencean?

**Comment by yosbel-penate** [comment]
La empresa tiene un solo almacen, pero si mañana compra otro, hay que modificar la clase empresa

**Comment by KevinPinoDelSol** [comment]
> La empresa tiene una lista de administradores, pero de que son administradores?

Administran las rutas y los silos.

**Comment by KevinPinoDelSol** [comment]
> La empresa tiene una lista de gerentes, pero que gerencean?

Son los responsables de Registrar todos los usuarios, almacenes, silos y vehículos al sistema, además de poder tener visión de ellos.

**Comment by yosbel-penate** [comment]
> > La empresa tiene una lista de administradores, pero de que son administradores?
> 
> Administran las rutas y los silos.

entonce por que no estan en los silos?

**Comment by yosbel-penate** [comment]
> 

yo nunca he visto un gerente que trabaje, registrar cosas no lo hacen las secretarias¨?

**Comment by KevinPinoDelSol** [comment]
> entonce por que no estan en los silos?

Porque los administradores pertenecen a la empresa, no están asignados a un Silo específico.

**Comment by KevinPinoDelSol** [comment]
> > 
> 
> yo nunca he visto un gerente que trabaje, registrar cosas no lo hacen las secretarias¨?

A alguien tenía que ponerle esa responsabilidad, le cambio el nombre a la clase?

**Comment by yosbel-penate** [comment]
> clas

en la descripcion que te di no dicen quien es el responsable de hacer eso? o es un rol que tienes que crear tu?

**Comment by yosbel-penate** [comment]
> > entonce por que no estan en los silos?
> 
> Porque los administradores pertenecen a la empresa, no están asignados a un Silo específico.

has visto alguna empresa donde los jefes no esten en el lugar que dirigen y anden todos junticos, diciendoce hoy me toca dirigir el silo 1, no me toca a mi¿

**Comment by KevinPinoDelSol** [comment]
Es una responsabilidad que tuve que crear yo, porque en la empresa ya está todo creado y registrado.

**Comment by KevinPinoDelSol** [comment]
> has visto alguna empresa donde los jefes no esten en el lugar que dirigen y anden todos junticos, diciendoce hoy me toca dirigir el silo 1, no me toca a mi¿

Claro que no, no tengo experiencia, pero bueno, voy a asignarle a cada silo un administrador.

**Comment by yosbel-penate** [comment]
> Es una responsabilidad que tuve que crear yo, porque en la empresa ya está todo creado y registrado.

a ya, entonces buscale un nombre menos significativo un gerente es alguien muy importante para estar pasando modelos

**Comment by KevinPinoDelSol** [comment]
> a ya, entonces buscale un nombre menos significativo un gerente es alguien muy importante para estar pasando modelos

Una pregunta, a la hora de generar la empresa tengo que tener al menos a una persona que me registre a las demás en el sistema.
En el constructor le pongo una secretaria o qué?

**Comment by yosbel-penate** [comment]
ese debe ser el administrador de sistema, el que pone a punto la aplicacion

**Comment by yosbel-penate** [comment]
ese debe ser el administrador de sistema, el que pone a punto la aplicacion

**Comment by KevinPinoDelSol** [comment]
Eso es otra clase o qué?

**Comment by KevinPinoDelSol** [comment]
@yosbel-penate Ya realizé los cambios y los subí al GitHub, están en el mismo branch.
