### ISSUE TITLE
Asignar un administrador a los silos

### ISSUE THREAD

**Issue by KevinPinoDelSol** [KevinPinoDelSol/Diagrama-Proyecto-DPOO#8]
>has visto alguna empresa donde los jefes no esten en el lugar que dirigen y anden todos junticos, diciendoce hoy me toca dirigir el silo 1, no me toca a mi¿

_Originally posted by @yosbel-penate in https://github.com/KevinPinoDelSol/Diagrama-Proyecto-DPOO/issues/2#issuecomment-1310863377_

**Comment by yosbel-penate** [comment]
Ademas, por que pones las relaciones y ademas los arreglos, cuando pones las relaciones estas generan el arreglo si es una relacion uno a mucho y un atributo si es uno a uno

**Comment by yosbel-penate** [comment]
poner la relacion es equivalente a decir que tiene el atributo

**Comment by KevinPinoDelSol** [comment]
> Ademas, por que pones las relaciones y ademas los arreglos, cuando pones las relaciones estas generan el arreglo si es una relacion uno a mucho y un atributo si es uno a uno

A mí no me funciona eso, generé código y no se me puso el atributo correspondiente.

**Comment by yosbel-penate** [comment]
eso debe ser algo que hay que activar

**Comment by KevinPinoDelSol** [comment]
Si usted sabe donde es, ya me dirá, hasta entonces sigo haciéndolo así.

**Comment by yosbel-penate** [comment]
Es tu VP que debe tener esa opcion desconfigurada,
